# Generated by Django 3.0 on 2020-09-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='computer',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='parsent_no',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='score',
            name='previous_no',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
