# Generated by Django 3.0 on 2020-09-25 08:54

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200925_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='parsent_no',
            field=models.CharField(default=student.models.random_string, max_length=5),
        ),
    ]
